name: Check Docs Site

on:
  push:
    branches:
      - "fr/**"
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "pnpm"
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Install Docs
        run: cd docs && pnpm install
      - name: lint
        run: cd docs && pnpm lint
      - name: Build
        run: cd docs && pnpm build
      - name: Storybook
        run: cd docs && pnpm build-storybook
