name: Check Docs Site

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  build:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Install Docs
        working-directory: docs/
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Build Docs
        working-directory: docs/
        run: pnpm build
