name: Check Docs Site

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-env
      - name: Install
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Install Docs
        run: cd docs && pnpm install --frozen-lockfile --prefer-offline
      - name: lint
        run: cd docs && pnpm lint
      - name: Build
        run: cd docs && pnpm build
