name: hardhat-viem CI

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/hardhat-viem-ci.yml"
      - "packages/hardhat-viem/**"
      - "packages/hardhat-core/**"
      - "packages/hardhat-common/**"
      - "config/**"
  pull_request:
    paths:
      - ".github/workflows/hardhat-verify-ci.yml"
      - "packages/hardhat-viem/**"
      - "packages/hardhat-core/**"
      - "packages/hardhat-common/**"
      - "config/**"
  workflow_dispatch:

defaults:
  run:
    working-directory: packages/hardhat-viem

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test_on_windows:
    name: Test hardhat-viem on Windows with Node 18
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-env
      - name: Install
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Build
        run: pnpm build
      - name: Run tests
        run: pnpm test

  test_on_macos:
    name: Test hardhat-viem on MacOS with Node 18
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-env
      - name: Install
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Build
        run: pnpm build
      - name: Run tests
        run: pnpm test

  test_on_linux:
    name: Test hardhat-viem on Ubuntu with Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20, 22]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-env
        with:
          node-version: ${{ matrix.node }}
      - name: Install
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Build
        run: pnpm build
      - name: Run tests
        run: pnpm test
