name: Lint

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: pnpm
          cache-dependency-path: |
            pnpm-lock.yaml
            docs/pnpm-lock.yaml
      - name: Install pnpm # pnpm is not insatlled by default in the CI
        run: npm install -g pnpm
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build
      - name: lint
        run: pnpm lint
      - name: Check dependency versions
        run: node scripts/check-dependencies.js
      - name: Install website
        working-directory: docs/
        run: pnpm install
      - name: Lint website
        working-directory: docs/
        run: pnpm lint
