name: Lint

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-env
      - name: Install
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Build
        run: pnpm build
      - name: lint
        run: pnpm lint
      - name: Check dependency versions
        run: node scripts/check-dependencies.js
      - name: Install website
        working-directory: docs/
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Lint website
        working-directory: docs/
        run: pnpm lint
